default:
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install --quiet -y git make build-essential
    - git clone https://github.com/vlang/v
    - cd v
    - make
    - ./v symlink

stages:
  - test
  - build
  - deploy  

format:
  stage: test
  script:
    - v fmt . -w
    - v test .

compile:
  stage: build
  script:
    - mkdir -p build
    - v . -o ./build/lext.exe
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
