stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - v fmt .
    - v test .

compile:
  stage: build
  script:
    - mkdir -p build
    - v . -o .\build\lext.exe
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
